name: aidafine
description: Aidafine
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.9.2
  auto_route_generator: ^7.3.2
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_remote_config: ^4.4.4
  firebase_vertexai: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.18.0
  json_annotation: ^4.9.0
  markdown: ^7.2.2
  path_provider: ^2.1.3
  record: ^5.0.5
  

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/