// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(Environment env) {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3wBWbVv4UnFLjp2PhQdW9SdNYmHcidY',
    appId: '1:180032486130:web:3f1cd7a4c5c3cd58e9ee6b',
    messagingSenderId: '180032486130',
    projectId: 'aidafine-eternalenterprise',
    authDomain: 'aidafine-eternalenterprise.firebaseapp.com',
    storageBucket: 'aidafine-eternalenterprise.appspot.com',
    measurementId: 'G-CB4909ZGNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JLLE2Sk2xxsbxNwlF59aSzHFFPIFZWE',
    appId: '1:180032486130:android:aebeba6a47e6894ce9ee6b',
    messagingSenderId: '180032486130',
    projectId: 'aidafine-eternalenterprise',
    storageBucket: 'aidafine-eternalenterprise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp0DplVodj_fMECiv4fgJE2WfwXPelhSs',
    appId: '1:180032486130:ios:e6eddf88692d0e76e9ee6b',
    messagingSenderId: '180032486130',
    projectId: 'aidafine-eternalenterprise',
    storageBucket: 'aidafine-eternalenterprise.appspot.com',
    androidClientId:
        '180032486130-uu58m817j0io5kdju53ffn58kgluagaf.apps.googleusercontent.com',
    iosClientId:
        '180032486130-tr428ctbt1gng9hlphh020p4p23v6bsh.apps.googleusercontent.com',
    iosBundleId: 'com.eternalenterprise.aidafine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp0DplVodj_fMECiv4fgJE2WfwXPelhSs',
    appId: '1:180032486130:ios:425ecc276ed8fc14e9ee6b',
    messagingSenderId: '180032486130',
    projectId: 'aidafine-eternalenterprise',
    storageBucket: 'aidafine-eternalenterprise.appspot.com',
    androidClientId:
        '180032486130-uu58m817j0io5kdju53ffn58kgluagaf.apps.googleusercontent.com',
    iosClientId:
        '180032486130-hff7gg8qf1dubiunalq4fnv669kgfuto.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}

/// Environment.
enum Environment {
  /// Development.
  development,

  /// Staging.
  staging,

  /// Production.
  production,
}
